name: 'url-shorten'

services:
  postgres:
    image: postgres:16-alpine
    container_name: urlshortener-postgres
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1gb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 2s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: urlshortener-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512mb

  app-1:
    build: .
    container_name: urlshortener-app-1
    environment: &app-env
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: urlshortener
      DB_USER: postgres
      DB_PASS: postgres
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    depends_on: &app-deps
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy: &app-deploy
      resources:
        limits:
          cpus: "1"
          memory: 512mb

  app-2:
    build: .
    container_name: urlshortener-app-2
    environment: *app-env
    depends_on: *app-deps
    deploy: *app-deploy

  nginx:
    image: nginx:alpine
    container_name: urlshortener-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app-1
      - app-2
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512mb

volumes:
  postgres_data:
  redis_data:
